import fs from 'node:fs/promises'
import path from 'node:path'
import { fileURLToPath } from 'node:url'

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..')
const sourceFiles = [
  'src/plugin/client-api.js',
  'src/plugin/client/styles.js',
  'src/plugin/client/workspace.js',
  'src/plugin/client/settings.js',
]

const moduleExports = [
  ['createSettingsClient', 'reduceHostsState'],
  ['CSS'],
  ['createRemoteWorkspaceAction'],
  ['createRemoteHostsTab'],
]
const toRuntimeSource = (source, names) => `${source
  .replace(/^export\s+(?=function\b|const\b|let\b|var\b|class\b)/gm, '')}\nmodule.exports = { ${names.map((name) => `${name}: typeof ${name} === 'undefined' ? undefined : ${name}`).join(', ')} }`

const sources = await Promise.all(sourceFiles.map(async (file, index) => toRuntimeSource(await fs.readFile(path.join(root, file), 'utf8'), moduleExports[index])))
const wrapper = `window.__ModuleLoader__.load({id:'dsh-remote-ssh-ops',factory:(require)=>{const load=(source)=>{const module={exports:{}};new Function('module','exports',source)(module,module.exports);return module.exports};const api=load(${JSON.stringify(sources[0])});const {CSS}=load(${JSON.stringify(sources[1])});const {createRemoteWorkspaceAction}=load(${JSON.stringify(sources[2])});const {createRemoteHostsTab}=load(${JSON.stringify(sources[3])});const React=require('react');const ui=require('@deepseek-ai/dsh-client-ui-primitives');return {name:'remote-ssh-ops-client',inject:['slots'],apply(ctx){const settingsApi=api.createSettingsClient();const Workspace=createRemoteWorkspaceAction(React,settingsApi,ui);const HostsTab=createRemoteHostsTab(React,settingsApi,ui);ctx.effect(()=>{const styleId='dsh-remote-ssh-ops-styles';const style=document.getElementById(styleId)??document.createElement('style');style.id=styleId;style.textContent=CSS;if(!style.isConnected)document.head.appendChild(style);return()=>style.remove()});ctx.slots.inject('settings.plugins.tab',()=>ctx.slots.register({name:'settings.plugins.tab',id:'remote-hosts',order:40,label:()=> '远程主机'},HostsTab));ctx.slots.inject('conversation.session.header.actions',()=>ctx.slots.register({name:'conversation.session.header.actions',id:'remote-workspace',order:12,label:()=> '远程工作台'},Workspace))}}}})`
await fs.writeFile(path.join(root, 'src/plugin/client.js'), `/* Generated by scripts/build-client.js. Edit src/plugin/client/*.js instead. */\n${wrapper}\n`, 'utf8')
